[target.x86_64-pc-windows-msvc]
image = ":latest"

[target.aarch64-pc-windows-msvc]
image = ":latest"

[target.x86_64-unknown-linux-gnu]
image = ":latest"

[target.aarch64-unknown-linux-gnu]
image = ":latest"

[target.x86_64-apple-darwin]
image = ":latest"

[target.aarch64-apple-darwin]
image = ":latest"