[target.x86_64-pc-windows-msvc]
zig = true
image = ":latest"

[target.aarch64-pc-windows-msvc]
zig = true
image = ":latest"

[target.x86_64-unknown-linux-gnu]
zig = true
image = ":latest"

[target.aarch64-unknown-linux-gnu]
zig = true
image = ":latest"

[target.x86_64-apple-darwin]
zig = true
image = ":latest"

[target.aarch64-apple-darwin]
zig = true
image = ":latest"